### ISSUE TITLE
Improvements to your blog-post

### ISSUE THREAD

**Issue by Kosai106** [Avix101/Mail-Server-Script#2]
Hi, just wanted to say that your guide and script really helped me out tonight. :)
However it didn't all go as smoothly as it could.

1st. The issue I got was that the script would refuse to run. This was due to an integer that was placed in parenthesis. I've created a Pull Request with the small fix.

2nd. On your blog, there's an error in your writing. Specifically in the section seen below - You accidentally misspelled "domains".

```
emacs super.sh

virtual_mailbox_doamins="yourdomain.com secondDomainIfYouHaveOne.com ..." (Only enter one if you only have one)
default_password="whateverYouChoose"
```

And 3rd. is a question.
Why go through the whole `mkdir mail_script` step, when the folder isn't even used?
Shouldn't that part instead be more like:

```
yum install emacs git -y

git clone https://github.com/Avix101/Mail-Server-Script.git

cd Mail-Server-Script

ls (to display contents)
```

**Comment by Avix101** [comment]
Thank you for the information! These fixes will go up soon.
