### ISSUE TITLE
Can't send/receive email

### ISSUE THREAD

**Issue by hoppy1977** [Avix101/Mail-Server-Script#6]
Hi,

I've been playing with this script for a while now but have been unable to send/receive emails.

I had no problems running the script, apart from having to make the change to 'bypass_virus_checks_maps' described by Kosai.

I was wondering if anyone else is having/had the same problem?

Cheers,
Hoppy.

**Comment by Avix101** [comment]
This will be fixed shortly! It has to do with a step that I forgot to include.

**Comment by Avix101** [comment]
Please try editing the security group associated with your instance, and allow for SSH, HTTP, HTTPS, SMTP, SMTPS, IMAP, IMAPS, PostgreSQL, Custom TCP Rule (Port: 587).
